### ISSUE TITLE
Custom notification CSS class

### ISSUE THREAD

**Issue by Clashsoft** [McFoggy/commonmark-ext-notifications#3]
Currently, the CSS class for generated `<div>`s is always one of `notification_{info,success,warning,error}`. It would be nice to allow a custom mapping, e.g. for Bootstrap classes: `alert alert-{info,success,warning,danger}`. Perhaps with a mapping function:

```java
Extension notificationExtension = NotificationsExtension.create().withClassMapper((Notification n) -> {
  return n == Notification.ERROR ? "alert alert-danger" : "alert alert-" + n.name().toLowerCase();
};
```

**Comment by McFoggy** [comment]
Added in new `1.1.0`.
